### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by leandrodreamer**
summary of changes on this branch:

- settings window
- main menu and pause menu are now separated to make it less confusing
- tool for download new songs from inside the game using beatsaver.com api
- sample playlist removed so there is a single playlist
- button to search songs on the playlist
- saber tail effect with semi-transparent shader that uses alpha scissors, wich should be faster (need testing on quest 1)
- events support for animated background
- background experimental texture that simulate radiance from the map lights using a single shader (need testing on quest 1)
- colors can be changed and affects all objects that uses the palette
- wall's new shader with alpha scissors semi-transparent shader (need testing on quest 1)
- new end score screen
- bug fixes and small improvements
- shader for cutted cubes that compute way faster than CSG

https://user-images.githubusercontent.com/26260718/104232094-cde42d80-541d-11eb-9290-757d537a4cdc.mp4

### CODE REVIEW

**Comment by NeoSpark314** [comment]
This looks really amazing! 

I started testing on Quest 1. My findings so far:

With glow deactivate the performance seems good even with the dynamic background and the saber tails activated (at least in songs with few notes). My suggestion would be to have glow deactivated by default for now.

When this is merged I can update to the newest oculus godot plugin. This will allow to check if we are running on a Quest 1 or Quest 2 and we could change the defaults depending on the device. This will also allow to activate 90hz mode on Quest 2. I think we should then also display a performance warning with glow on Quest 1 (or remove the option completly on Quest 1).

Performance with walls so far looked fine on Quest 1.

**Comment by leandrodreamer** [comment]
there is it, also reduced background prerendered light map size so it uses less vram
i'll add an option to delete downloaded songs that i think is needed and after that and some code clean i think it will be ready to review

**Comment by leandrodreamer** [comment]
i think i can replace the cube cut function for a shader based cut that will be quite a lot faster.

**Comment by leandrodreamer** [comment]
performance comparative between CSG and shader performance, i am having some troubles to get the cut angle, it kind of work right now but sometimes (when the cut is far from good) it shows the cut on the wrong direction, how could i correctly get the cut angle relative to the cube orientation?

https://user-images.githubusercontent.com/26260718/104383894-96997d80-54fe-11eb-9b74-6ba119e914a1.mp4

**Comment by leandrodreamer** [comment]
ok i figure it out and now is pretty accurate, i think that that's the last change that i wanted to do

https://user-images.githubusercontent.com/26260718/104394652-0e72a280-5515-11eb-8173-7b1d27b0cc33.mp4

**Comment by NeoSpark314** [comment]
Awesome! Great work. I think we can merge your changes now and if you want to do more changes you just create new pull requests for individual improvements.

**Comment by leandrodreamer** [comment]
i agree :)

**Comment by NeoSpark314** [comment]
Done. If you want to continue making changes you should delete your current branch and create a new one from master.

**Pull request merged**
