### PR TITLE
BeepCube: Cut particles, refactored shader, cut physics etc...

### PR DESCRIPTION
**Pull request by Firepal**
- BeepCube material was almost half-rewritten:
  - Cut white-margin rotation is done using a rotation matrix instead of raw arithmetic and if-statements. (Previous method also exhibited some strange artefacts..)
  - Moved cut white-margin rotation code from pixel shader to vertex shader.
  - Use `discard` call for alpha scissoring.
  - Removed excess uniforms from SpatialMaterial conversion process.
  - Re-organized the shader for readability.

- The rigid body forces applied to the cutted cube halfs no longer uses the  `cutplane` variable. Instead we use the 2D cutplane (also used to compute the "cut angle").
  - This is less accurate than using `cutplane`, but it's prettier, and I couldn't find out how to use it to generate a rotation matrix. I also added side-forces to really split the halfs apart.

- Slicing a cube now makes cool particle effects show up!
  One particle effect is radial, and the other follows the cut direction.

### CODE REVIEW

**Comment by NeoSpark314** [comment]
With this change I now get black cubes (Quest 1) also on desktop visible; do you maybe know what might cause this? 

org dammertz vr godot_beep_saber-20210906-185127

I don't have time right now to investigate but hopefully later.

**Comment by Firepal** [comment]
I think the BeepCube texture isn't set in the material, I was sure of it though? I'm gonna check

**Comment by Firepal** [comment]
Uh, looks fine...
image

**Comment by NeoSpark314** [comment]
This is how it looks for me on desktop right now with master:

image

Maybe it's a problem with my godot version; but for Quest export I use the included .apk;

**Comment by NeoSpark314** [comment]
Now it works for me; I had some changes due to testing the previous PR merges locally I missed; git checkout . helped:

image

Thx for this nice contribution!!

**Comment by Firepal** [comment]
Aha, git can be silly sometimes :)

**Pull request merged**
